=== Disalg-ICS-NJU/MIPA/trunk/config/predicate/predicate.dtd
<!ELEMENT predicate (CGSs, specification)>
<!ATTLIST predicate type (SCP|WCP|OGA|LP|CADA|SEQUENCE|SURSEQUENCE|CTL|WINDOWSEQUENCE|TCTL) #REQUIRED>

<!-- CGS definition -->
<!ELEMENT CGSs (CGS)+>
<!ELEMENT CGS (LP)+>
<!ATTLIST CGS 
	name CDATA #REQUIRED
	value (conjunction|disjunction) #IMPLIED>

<!-- local predicate definition -->
<!ELEMENT LP (formula)>
<!ATTLIST LP 
	windowSize CDATA #IMPLIED>
<!ELEMENT formula ((quantifier, formula)|(formula, binary, formula)|(unary, formula)|atom)>

<!-- quantifier contains symbol and variable -->
<!ELEMENT quantifier (#PCDATA)>
<!ATTLIST quantifier value (universal|existential) #REQUIRED>
<!ELEMENT binary EMPTY>
<!ATTLIST binary value (conjunction|disjunction|imply|EU|AU) #REQUIRED>
<!ELEMENT unary EMPTY>
<!ATTLIST unary value (not|EX|EF|EG|AX|AF|AG) #IMPLIED>
<!ATTLIST unary leftOperator (greater-than|greater-or-equal) #IMPLIED>
<!ATTLIST unary leftBound CDATA #IMPLIED>
<!ATTLIST unary rightOperator (less-than|less-or-equal) #IMPLIED>
<!ATTLIST unary rightBound CDATA #IMPLIED>

<!-- operator: ==, great-than, not-great-than, less-than, not-less-than, etc. -->
<!ELEMENT atom EMPTY>
<!ATTLIST atom
	operator CDATA #REQUIRED
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

<!-- specification definition -->
<!ELEMENT specification ((prefix, GSE)|(CTLFormula)|(TCTLFormula))>
<!ELEMENT prefix EMPTY>
<!ATTLIST prefix value (def|pos) #REQUIRED>

<!ELEMENT GSE (element+, global)>
<!ATTLIST GSE value (conjunction|disjunction) #REQUIRED>

<!ELEMENT element (zeroOrMore|oneOrMore|choice|optional|cgs)>
<!ELEMENT zeroOrMore (element)+>
<!ELEMENT oneOrMore (element)+>
<!ELEMENT choice (element,(element)+)>
<!ELEMENT optional (element)+>
<!ELEMENT cgs EMPTY>
<!ATTLIST cgs name CDATA #REQUIRED>
<!ELEMENT global (#PCDATA)>

<!ELEMENT CTLFormula (cgs | (CTLFormula,binary,CTLFormula) | (unary, CTLFormula))>

<!ELEMENT TCTLFormula (cgs | (unary, TCTLFormula))>

=== Disalg-ICS-NJU/MIPA/trunk/predicate_oga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "dtd/predicate.dtd">
<predicate type="OGA">
  <prefix value="def" />
  <GSE value="conjunction">
    <CGS value="conjunction">
      <LP>
	<formula>
	  <atom operator="great-than" name="temperature" value="27" />
	</formula>
      </LP>
      <LP>
	<formula>
	  <atom operator="not-contain" name="RFID" value="tag_00001" />
	</formula>
      </LP>
    </CGS>
    <CGS value="conjunction">
    	<LP>
    		<formula>
    			<atom operator="less-than" name="temperature_1" value="40" />
    		</formula>
    	</LP>
    	<LP>
    		<formula>
    			<atom operator="contain" name="RFID_1" value="tag_00002" />
    		</formula>
    	</LP>
    </CGS>
    <global>g</global>
  </GSE>
</predicate>

=== Disalg-ICS-NJU/MIPA/trunk/config/predicate/predicate_scp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="SCP">
  <prefix value="def" />
  <GSE value="conjunction">
    <CGS value="conjunction">
      <LP>
	<formula>
	<!--	  <atom operator="great-than" name="temperature" value="27" />-->
	<atom operator="great-than" name="light" value="500" />
	</formula>
      </LP>
      <LP>
	<formula>
	  <atom operator="not-contain" name="RFID" value="tag_00001" />
	</formula>
      </LP>
    </CGS>
    <global>g</global>
  </GSE>
</predicate>

=== Disalg-ICS-NJU/MIPA/trunk/config/predicate/predicate_tctl_af_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd" >
<predicate type="TCTL">
  <CGSs>
	<CGS name="a" value="conjunction">
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_1" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_2" value="500" />
			</formula>
		</LP>
		<!--<LP>
			<formula>
				<atom operator="greater-than" name="distance_3" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_4" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_5" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_6" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_7" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_8" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_9" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_10" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_11" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_12" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_13" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_14" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_15" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_16" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_17" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_18" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_19" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_20" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_21" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_22" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_23" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_24" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_25" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_26" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_27" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_28" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_29" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="greater-than" name="distance_30" value="500" />
			</formula>
		</LP>-->
	</CGS>
  </CGSs>
  <specification>
  		<TCTLFormula>
     		<unary value="AF" leftOperator="greater-than" leftBound = "0" rightOperator="less-than" rightBound = "15000"/>
     		<TCTLFormula>
     			<cgs name="a"/>
     		</TCTLFormula>
   		</TCTLFormula>
	</specification>
</predicate>
