=== Disalg-ICS-NJU/MIPA/tags/1.3.0/config/sensors/sensor.dtd
<!ELEMENT sensor (name, id, class, location, ValueType, DataSchema, DataDisseminate, arguments)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT ValueType (#PCDATA)>
<!ELEMENT DataSchema EMPTY>
<!ATTLIST DataSchema type (push|pull) #REQUIRED>
<!ELEMENT DataDisseminate EMPTY>
<!ATTLIST DataDisseminate time CDATA #REQUIRED>
<!ATTLIST DataDisseminate lazy (true|false) #REQUIRED>
<!ELEMENT arguments (argument)+>
<!-- all arguments are string, user can narrow their types in code -->
<!ELEMENT argument (#PCDATA)>
<!--<!ELEMENT ArgumentType (#PCDATA)>-->

=== Disalg-ICS-NJU/MIPA/trunk/config/sensors/temperature.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>temperature</name>
  <id>temperature</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationTemperature</class>
  <location>nju</location>
  <ValueType>Double</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy="true" />
  <arguments>
	<argument>data/temperature</argument>
	<ArgumentType>String</ArgumentType>
  </arguments>
</sensor>

=== Disalg-ICS-NJU/MIPA/tags/1.3.0/config/sensors/light.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>light</name>
  <id>light</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationLight</class>
  <location>nju</location>
  <ValueType>Double</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy="true" />
  <arguments>
	<argument>data/light</argument>
  </arguments>
</sensor>

=== Disalg-ICS-NJU/MIPA/tags/1.3.3/config/sensors/RFID_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>RFID_1</name>
  <id>RFID_1</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationRFID</class>
  <location>nju</location>
  <ValueType>String</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy = "false" />
  <arguments>
	<argument>data/RFID_1</argument>
  </arguments>
</sensor>

=== Disalg-ICS-NJU/MIPA/trunk/config/sensors/light_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>light_1</name>
  <id>light_1</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationLight</class>
  <location>nju</location>
  <ValueType>Double</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy="true" />
  <arguments>
	<argument>data/light_1</argument>
  </arguments>
</sensor>

=== Disalg-ICS-NJU/MIPA/config/sensors/temperature_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>temperature_1</name>
  <id>temperature_1</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationTemperature</class>
  <location>nju</location>
  <ValueType>Double</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy="true" />
  <arguments>
	<argument>data/temperature_1</argument>
  </arguments>
</sensor>

=== Disalg-ICS-NJU/MIPA/config/sensors/d_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>d_2</name>
  <id>d_2</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationDistanceWithTime</class>
  <location>nju</location>
  <ValueType>Double</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy="true" />
  <arguments>
	<argument>data/d_2</argument>
  </arguments>
</sensor>

=== Disalg-ICS-NJU/MIPA/config/sensors/distance_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>distance_2</name>
  <id>distance_2</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationDistanceWithTime</class>
  <location>nju</location>
  <ValueType>Double</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy="true" />
  <arguments>
	<argument>data/distance_2</argument>
  </arguments>
</sensor>

=== Disalg-ICS-NJU/MIPA/trunk/config/sensors/RFID.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "sensor.dtd">
<sensor>
  <name>RFID</name>
  <id>RFID</id>
  <class>net.sourceforge.mipa.eca.sensor.SimulationRFID</class>
  <location>nju</location>
  <ValueType>String</ValueType>
  <DataSchema type="push" />
  <DataDisseminate time="1" lazy="false" />
  <arguments>
	<argument>data/RFID</argument>
  </arguments>
</sensor>
