=== Disalg-ICS-NJU/MIPA/tags/demo-0.1/trunk/dtd/predicate.dtd
<!ELEMENT predicate (prefix, GSE)>
<!ELEMENT prefix EMPTY>
<!ATTLIST prefix value (def|pos) #REQUIRED>

<!ELEMENT GSE (CGS, global)+>
<!ATTLIST GSE value (conjunction|disjunction) #REQUIRED>

<!ELEMENT CGS (LP)+>
<!ATTLIST CGS value (conjunction|disjunction) #REQUIRED>

<!ELEMENT global (#PCDATA)>

<!-- local predicate definition -->
<!ELEMENT LP (formula)>
<!ELEMENT formula ((quantifier, formula)|(formula, binary, formula)|(unary, formula)|atom)>
<!-- quantifier contains symbol and variable -->
<!ELEMENT quantifier (#PCDATA)>
<!ATTLIST quantifier value (universal|existential) #REQUIRED>

<!ELEMENT binary EMPTY>
<!ATTLIST binary value (conjunction|disjunction|impliction) #REQUIRED>

<!ELEMENT unary EMPTY>
<!ATTLIST unary value (not) #IMPLIED>

<!-- operator: ==, great-than, not-great-than, less-than, not-less-than, etc. -->
<!ELEMENT atom EMPTY>
<!ATTLIST atom
  operator CDATA #REQUIRED
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

=== Disalg-ICS-NJU/MIPA/tags/0.3/predicate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "dtd/predicate.dtd">
<predicate>
  <prefix value="def" />
  <GSE value="conjunction">
    <CGS value="conjunction">
      <LP>
	<formula>
	  <atom operator="great-than" name="temperature" value="27" />
	</formula>
      </LP>
      <LP>
	<formula>
	  <atom operator="not-contain" name="RFID" value="tag_00001" />
	</formula>
      </LP>
    </CGS>
    <global>g</global>
  </GSE>
</predicate>

=== Disalg-ICS-NJU/MIPA/tags/1.2/config/predicate/predicate_oga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="OGA">
  <prefix value="def" />
  <GSE value="conjunction">
    <CGS value="conjunction">
      <LP>
	<formula>
	  <atom operator="great-than" name="temperature" value="30" />
	</formula>
      </LP>
      <LP>
	<formula>
	  <atom operator="contain" name="RFID" value="tag_00001" />
	</formula>
      </LP>
    </CGS>
    <CGS value="conjunction">
    	<LP>
    		<formula>
    			<atom operator="great-than" name="temperature_1" value="30" />
    		</formula>
    	</LP>
    	<LP>
    		<formula>
    			<atom operator="contain" name="RFID_1" value="tag_00001" />
    		</formula>
    	</LP>
    </CGS>
    <global>g</global>
  </GSE>
</predicate>
