=== Disalg-ICS-NJU/MIPA/branches/ctl/hengxin/config/predicate/predicate.dtd
<!ELEMENT predicate (CGSs, specification)>
<!ATTLIST predicate type (SCP|WCP|OGA|LP|CADA|SEQUENCE) #REQUIRED>

<!-- CGS definition -->
<!ELEMENT CGSs (CGS)+>
<!ELEMENT CGS (LP)+>
<!ATTLIST CGS 
	name CDATA #REQUIRED
	value (conjunction|disjunction) #IMPLIED>

<!-- local predicate definition -->
<!ELEMENT LP (formula)>
<!ELEMENT formula ((quantifier, formula)|(formula, binary, formula)|(unary, formula)|atom)>

<!-- quantifier contains symbol and variable -->
<!ELEMENT quantifier (#PCDATA)>
<!ATTLIST quantifier value (universal|existential) #REQUIRED>
<!ELEMENT binary EMPTY>
<!ATTLIST binary value (conjunction|disjunction|imply) #REQUIRED>
<!ELEMENT unary EMPTY>
<!ATTLIST unary value (not) #IMPLIED>

<!-- operator: ==, great-than, not-great-than, less-than, not-less-than, etc. -->
<!ELEMENT atom EMPTY>
<!ATTLIST atom
	operator CDATA #REQUIRED
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

<!-- specification definition -->
<!ELEMENT specification (prefix, GSE)>
<!ELEMENT prefix EMPTY>
<!ATTLIST prefix value (def|pos) #REQUIRED>

<!ELEMENT GSE (element+, global)>
<!ATTLIST GSE value (conjunction|disjunction) #REQUIRED>

<!ELEMENT element (zeroOrMore|oneOrMore|choice|optional|cgs)>
<!ELEMENT zeroOrMore (element)+>
<!ELEMENT oneOrMore (element)+>
<!ELEMENT choice (element,(element)+)>
<!ELEMENT optional (element)+>
<!ELEMENT cgs EMPTY>
<!ATTLIST cgs name CDATA #REQUIRED>
<!ELEMENT global (#PCDATA)>

=== Disalg-ICS-NJU/MIPA/branches/ctl/hengxin/config/predicate/ctl/predicate_ctl_au_experiment0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "../predicate.dtd" >
<predicate type="CTL">
  <CGSs>
	<CGS name="a" value="conjunction">
		<LP>
			<formula>
				<atom operator="great-than" name="light" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="contain" name="RFID" value="tag_00001" />
			</formula>
		</LP>
	</CGS>
	<CGS name="b" value="conjunction">
		<LP>
			<formula>
				<atom operator="less-than" name="light_1" value="500" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="contain" name="RFID_1" value="tag_00001" />
			</formula>
		</LP>
	</CGS>
  </CGSs>
  
  	<specification>
  		<CTLFormula>
     		<CTLFormula>
     			<unary value="not" />
     			<CTLFormula>
     				<cgs name="a"/>
     			</CTLFormula>
     		</CTLFormula>
     		<binary value="AU" />
     		<CTLFormula>
     			<cgs name="b"/>
     		</CTLFormula>
   		</CTLFormula>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/branches/Lattice-SimpleSequence/config/predicate/predicate_simplesequence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="SIMPLESEQUENCE">
	<CGSs>
		<CGS name="a" value="conjunction">
			<LP>
				<formula>
					<atom operator="great-than" name="light" value="500" />
				</formula>
			</LP>
			<LP>
				<formula>
					<atom operator="contain" name="RFID" value="tag_00001" />
				</formula>
			</LP>
		</CGS>
		<CGS name="b" value="conjunction">
			<LP>
				<formula>
					<atom operator="less-than" name="light_1" value="500" />
				</formula>
			</LP>
			<LP>
				<formula>
					<atom operator="not-contain" name="RFID_1" value="tag_00001" />
				</formula>
			</LP>
		</CGS>
	</CGSs>
	<specification>
		<prefix value="def" />
		<GSE value="conjunction">
			<element>
				<cgs name="a"/>
			</element>
			<element>
				<cgs name="b"/>
			</element>
			<global>g</global>
  		</GSE>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/tags/1.3.2/config/predicate/predicate_wcp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="WCP">
	<CGSs>
		<CGS name = "a" value = "conjunction">
			<LP>
				<formula>
	 				<atom operator="great-than" name="light" value="500" />
				</formula>
      		</LP>
      		<LP>
				<formula>
	  				<atom operator="not-contain" name="RFID" value="tag_00001" />
				</formula>
      		</LP>
		</CGS>
	</CGSs>
	<specification>
		<prefix value="pos" />
		<GSE value="conjunction">
			<element>
				<cgs name = "a"/>
			</element>
			<global>g</global>
		</GSE>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/branches/mipa-lattice/config/predicate/predicate_wcp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="WCP">
  <prefix value="def" />
  <GSE value="conjunction">
    <CGS value="conjunction">
      <LP>
	<formula>
	  <atom operator="great-than" name="temperature" value="27" />
	</formula>
      </LP>
      <LP>
	<formula>
	  <atom operator="contain" name="RFID" value="tag_00001" />
	</formula>
      </LP>
      <LP>
	<formula>
	  <atom operator="less-than" name="temperature_1" value="27" />
	</formula>
      </LP>
      <LP>
	<formula>
	  <atom operator="not-contain" name="RFID_1" value="tag_00001" />
	</formula>
      </LP>
    </CGS>
    <global>g</global>
  </GSE>
</predicate>

=== Disalg-ICS-NJU/MIPA/tags/1.3.3/config/predicate/predicate_re.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="SURSEQUENCE">
	<CGSs>
		<CGS name="e" value="conjunction">
			<LP><formula><atom operator="great-than" name="light" value="500" /></formula></LP>
		</CGS>
		<CGS name="f" value="conjunction">
			<LP><formula><atom operator="less-than" name="light_1" value="500" /></formula></LP>
		</CGS>
	</CGSs>
	<specification>
		<prefix value="pos" />
		<GSE value="conjunction">
			<element><oneOrMore><element><cgs name="e"/></element></oneOrMore></element>
			<element><cgs name="f"/></element>
			<global>g</global>
  		</GSE>
	</specification>
</predicate>
