=== Disalg-ICS-NJU/MIPA/branches/ctl/hengxin/config/predicate/predicate.dtd
<!ELEMENT predicate (CGSs, specification)>
<!ATTLIST predicate type (SCP|WCP|OGA|LP|CADA|SEQUENCE) #REQUIRED>

<!-- CGS definition -->
<!ELEMENT CGSs (CGS)+>
<!ELEMENT CGS (LP)+>
<!ATTLIST CGS 
	name CDATA #REQUIRED
	value (conjunction|disjunction) #IMPLIED>

<!-- local predicate definition -->
<!ELEMENT LP (formula)>
<!ELEMENT formula ((quantifier, formula)|(formula, binary, formula)|(unary, formula)|atom)>

<!-- quantifier contains symbol and variable -->
<!ELEMENT quantifier (#PCDATA)>
<!ATTLIST quantifier value (universal|existential) #REQUIRED>
<!ELEMENT binary EMPTY>
<!ATTLIST binary value (conjunction|disjunction|imply) #REQUIRED>
<!ELEMENT unary EMPTY>
<!ATTLIST unary value (not) #IMPLIED>

<!-- operator: ==, great-than, not-great-than, less-than, not-less-than, etc. -->
<!ELEMENT atom EMPTY>
<!ATTLIST atom
	operator CDATA #REQUIRED
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

<!-- specification definition -->
<!ELEMENT specification (prefix, GSE)>
<!ELEMENT prefix EMPTY>
<!ATTLIST prefix value (def|pos) #REQUIRED>

<!ELEMENT GSE (element+, global)>
<!ATTLIST GSE value (conjunction|disjunction) #REQUIRED>

<!ELEMENT element (zeroOrMore|oneOrMore|choice|optional|cgs)>
<!ELEMENT zeroOrMore (element)+>
<!ELEMENT oneOrMore (element)+>
<!ELEMENT choice (element,(element)+)>
<!ELEMENT optional (element)+>
<!ELEMENT cgs EMPTY>
<!ATTLIST cgs name CDATA #REQUIRED>
<!ELEMENT global (#PCDATA)>

=== Disalg-ICS-NJU/MIPA/tag/config/predicate/predicate_sursequence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="SURSEQUENCE">
	<CGSs>
		<CGS name="a" value="conjunction">
			<LP>
				<formula>
					<atom operator="great-than" name="light" value="500" />
				</formula>
			</LP>
			<LP>
				<formula>
					<atom operator="contain" name="RFID" value="tag_00001" />
				</formula>
			</LP>
		</CGS>
		<CGS name="b" value="conjunction">
			<LP>
				<formula>
					<atom operator="less-than" name="light_1" value="500" />
				</formula>
			</LP>
			<LP>
				<formula>
					<atom operator="not-contain" name="RFID_1" value="tag_00001" />
				</formula>
			</LP>
		</CGS>
		<CGS name="c" value="conjunction">
			<LP>
				<formula>
					<atom operator="great-than" name="light_2" value="500" />
				</formula>
			</LP>
			<LP>
				<formula>
					<atom operator="contain" name="RFID_2" value="tag_00001" />
				</formula>
			</LP>
		</CGS>
		<CGS name="d" value="conjunction">
			<LP>
				<formula>
					<atom operator="less-than" name="light_3" value="500" />
				</formula>
			</LP>
			<!--<LP>
				<formula>
					<atom operator="not-contain" name="RFID_3" value="tag_00001" />
				</formula>
			</LP>
		--></CGS>
	</CGSs>
	<specification>
		<prefix value="pos" />
		<GSE value="conjunction">
			<element>
				<oneOrMore>
					<element>
						<cgs name="a"/>
					</element>
				</oneOrMore>
			</element>
			<element>
				<cgs name="b"/>
			</element>
			<global>g</global>
  		</GSE>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/config/predicate/predicate_tctl_af.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd" >
<predicate type="TCTL">
  <CGSs>
	<CGS name="d" value="conjunction">
		<LP>
			<formula>
				<atom operator="less-than" name="d_1" value="1100" />
			</formula>
		</LP>
		<LP>
			<formula>
				<atom operator="less-than" name="d_2" value="1500" />
			</formula>
		</LP>
	</CGS>
  </CGSs>
  <specification>
  		<TCTLFormula>
     		<unary value="AF" leftOperator="greater-than" leftBound = "0" rightOperator="less-than" rightBound = "10000"/>
     		<TCTLFormula>
     			<cgs name="d"/>
     		</TCTLFormula>
   		</TCTLFormula>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/config/predicate/predicate_ctl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd" >
<predicate type="CTL">
  <CGSs>
	<CGS name="g" value="conjunction">
		<LP><formula><atom operator="less-than" name="light" value="500" /></formula></LP>
	</CGS>
	<CGS name="h" value="conjunction">
		<LP><formula><atom operator="contain" name="RFID" value="tag_00001" /></formula></LP>
	</CGS>
  </CGSs>
  	<specification>
  		<CTLFormula>
     		<CTLFormula><cgs name="g"/></CTLFormula>
     		<binary value="EU" />
     		<CTLFormula><cgs name="h"/></CTLFormula>
   		</CTLFormula>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/config/predicate/predicate_wcp_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="WCP">
	<CGSs>
		<CGS name = "m" value = "conjunction">
			<LP>
				<formula>
	 				<atom operator="great-than" name="light_1" value="500" />
				</formula>
      		</LP>
      		<LP>
				<formula>
	  				<atom operator="not-contain" name="RFID_1" value="tag_00001" />
				</formula>
      		</LP>
		</CGS>
	</CGSs>
	<specification>
		<prefix value="pos" />
		<GSE value="conjunction">
			<element>
				<cgs name = "m"/>
			</element>
			<global>g</global>
		</GSE>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/tag/config/predicate/predicate_ctl_eu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd" >
<predicate type="CTL">
  <CGSs>
	<CGS name="d" value="conjunction">
		<LP>
			<formula>
				<atom operator="less-than" name="light" value="500" />
			</formula>
		</LP>
<!-- 		<LP> -->
<!-- 			<formula> -->
<!-- 				<atom operator="contain" name="RFID_1" value="tag_00001" /> -->
<!-- 			</formula> -->
<!-- 		</LP> -->
	</CGS>
	<CGS name="e" value="conjunction">
<!-- 		<LP> -->
<!-- 			<formula> -->
<!-- 				<atom operator="greater-than" name="light_1" value="500" /> -->
<!-- 			</formula> -->
<!-- 		</LP> -->
		<LP>
			<formula>
				<atom operator="contain" name="RFID" value="tag_00001" />
			</formula>
		</LP>
	</CGS>
  </CGSs>
  
  	<specification>
  		<CTLFormula>
     		<CTLFormula>
       			<cgs name="d"/>
     		</CTLFormula>
     		<binary value="EU" />
     		<CTLFormula>
     			<cgs name="e"/>
     		</CTLFormula>
   		</CTLFormula>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/branches/mipa-general-condition/config/predicate/predicate_wcp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="WCP">
	<prefix value="def" />
	<GSE value="conjunction">
		<CGS value="conjunction">
			<LP>
				<formula>
					<atom operator="great-than" name="temperature" value="27" />
				</formula>
			</LP>
			<LP>
				<formula>
					<atom operator="not-contain" name="RFID" value="tag_00001" />
				</formula>
			</LP>
			<LP>
				<formula>
					<formula>
						<quantifier value="universal"/>
						<formula>
							<atom operator="great-than" name="temperature" value="25" />
						</formula>
					</formula>
					<binary value="conjunction"/>
					<formula>
						<unary value="not"/>
						<formula>
							<atom operator="great-than" name="temperature" value="27" />
						</formula>
					</formula>
				</formula>
			</LP>
		</CGS>
		<global>g</global>
	</GSE>
</predicate>

=== Disalg-ICS-NJU/MIPA/tag/config/predicate/predicate_scp_fault.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="SCP">
	<CGSs>
		<CGS name = "b" value = "conjunction">
			<LP><atom operator="great-than" name="light" value="500" /></LP>
			<LP><atom operator="not-contain" name="RFID" value="tag_00001" /></LP>
		</CGS>
	</CGSs>
	<specification>
		<prefix value="def" />
		<GSE value="conjunction">
			<element><cgs name = "b"/></element>
			<global>g</global>
		</GSE>
	</specification>
</predicate>

=== Disalg-ICS-NJU/MIPA/config/predicate/predicate_windowsequence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE predicate SYSTEM "predicate.dtd">
<predicate type="WINDOWSEQUENCE">
	<CGSs>
		<CGS name="a" value="conjunction">
			<LP windowSize="2">
				<formula>
					<atom operator="great-than" name="light" value="500" />
				</formula>
			</LP>
			<LP windowSize="2">
				<formula>
					<atom operator="contain" name="RFID" value="tag_00001" />
				</formula>
			</LP>
			<!-- <LP windowSize="2">
				<formula>
					<atom operator="less-than" name="light_1" value="500" />
				</formula>
			</LP>
			<LP windowSize="2">
				<formula>
					<atom operator="not-contain" name="RFID_1" value="tag_00001" />
				</formula>
			</LP>
			<LP windowSize="2">
				<formula>
					<atom operator="great-than" name="light_2" value="500" />
				</formula>
			</LP>
			<LP windowSize="2">
				<formula>
					<atom operator="contain" name="RFID_2" value="tag_00001" />
				</formula>
			</LP>
			<LP windowSize="2">
				<formula>
					<atom operator="less-than" name="light_3" value="500" />
				</formula>
			</LP>
			<LP windowSize="2">
				<formula>
					<atom operator="not-contain" name="RFID_3" value="tag_00001" />
				</formula>
			</LP>
			<LP windowSize="2">
				<formula>
					<atom operator="great-than" name="light_4" value="500" />
				</formula>
			</LP> -->
		</CGS>
	</CGSs>
	<specification>
		<prefix value="def" />
		<GSE value="conjunction">
			<element>
				<oneOrMore>
					<element>
						<cgs name="a" />
					</element>
				</oneOrMore>
			</element>
			<!--<element>
				<cgs name="b" />
			</element>
			<element>
				<cgs name="c" />
			</element>
			--><global>g</global>
		</GSE>
	</specification>
</predicate>
